### ISSUE TITLE
[FR] Add "state_class: measurement" for sensors

### ISSUE THREAD

**Issue by ildar170975** [Limych/ha-gismeteo#194]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/Limych/ha-gismeteo/issues?q=is%3Aissue+label%3A%22enhancement%22+).

### Is your feature request related to a problem? Please describe.

Please add `state_class: measurement` for created sensors.
Exceptions:
 - "forecast" sensors;
 - non-numerical sensors.

### Describe the solution you'd like

see above

### Describe alternatives you've considered

```
homeassistant:
  customize_glob:
    sensor.home_gismeteo_*:
      state_class: measurement
```

### Additional context

none
