### ISSUE TITLE
не показывает погоду

### ISSUE THREAD

**Issue by schel4ok** [Limych/ha-gismeteo#9]
* Version of the Home Assistant: 0.117.5
* Version of the custom component: 2.0.22

**Configuration**
```yaml

homeassistant:
  name: Home Assistant
  latitude: 55.949571
  longitude: 37.924716
  elevation: 0
  unit_system: metric
  time_zone: Europe/Moscow

default_config:

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

weather:
  - platform: gismeteo

```

**Describe the bug**
Я установил пакет hass.io с центра пакетов Synology. 
Потом в /hass.io/homeassistant/custom_components/gismeteo скопировал все файлы из \ha-gismeteo-master\custom_components\gismeteo

Но в списке интеграций gismeteo не появилась и добавить панель погоды не могу.
![ha](https://user-images.githubusercontent.com/10367464/98481304-5bcb4e80-220a-11eb-9e62-decbfdf802fe.JPG)

**Debug log**
в разделе /config/logs я вижу такие ошибки

```log
Logger: custom_components.gismeteo
Source: custom_components/gismeteo/__init__.py:165
Integration: Gismeteo (documentation)
First occurred: 20:59:05 (1 occurrences)
Last logged: 20:59:05
Can't detect nearest city! 


Logger: homeassistant.loader
Source: loader.py:463
First occurred: 20:59:00 (1 occurrences)
Last logged: 20:59:00
You are using a custom integration for gismeteo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant. 
```

**Comment by Limych** [comment]
В списке интеграцией компонента и не должно быть, т.к. у него нет графического интерфейса настройки.

Похоже, почему-то компонент не может связаться с сервером Гисметео.

Попробуйте включить отладку, добавив в конфиги следующий код:
```yaml
logger:
  logs:
    custom_components.gismeteo: debug
```
